name: CI - Pull Request Tests

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'tests/**'
      - 'utils/**'
      - 'schemas/**'
      - 'playwright.config.ts'
      - 'package.json'
      - 'package-lock.json'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: TypeScript type check
        run: npx tsc --noEmit
        
      - name: Check code formatting
        run: npx prettier --check "tests/**/*.ts" "utils/**/*.ts"

  api-tests:
    runs-on: ubuntu-latest
    needs: lint-and-typecheck
    strategy:
      matrix:
        node-version: [20, 22]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
          
      - name: Create test results directory
        run: mkdir -p test-results
        
      - name: Run API Tests
        run: npx playwright test
        env:
          BASE_URL: https://petstore.swagger.io/v2
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ci-test-results-node-${{ matrix.node-version }}-${{ github.run_number }}
          path: |
            test-results/
            playwright-report/
          retention-days: 7
          
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ci-playwright-report-node-${{ matrix.node-version }}-${{ github.run_number }}
          path: playwright-report/
          retention-days: 7

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run security audit
        run: npm audit --audit-level moderate
        
      - name: Check for vulnerabilities
        run: npm audit --audit-level high --json > security-report.json
        continue-on-error: true
        
      - name: Upload security report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-report-${{ github.run_number }}
          path: security-report.json
          retention-days: 30

  test-summary:
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck, api-tests, security-scan]
    if: always()
    steps:
      - name: Test Summary
        run: |
          echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Lint & TypeCheck: ${{ needs.lint-and-typecheck.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- API Tests: ${{ needs.api-tests.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Security Scan: ${{ needs.security-scan.result }}" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ needs.api-tests.result }}" == "success" ]; then
            echo "✅ All tests passed!" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Some tests failed!" >> $GITHUB_STEP_SUMMARY
          fi