name: Dev Environment Tests

on:
  schedule:
    # Run every 2 hours on weekdays (Monday to Friday)
    - cron: '0 */2 * * 1-5'
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - user
          - pet
          - store

jobs:
  api-tests:
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install
          
      - name: Create test results directory
        run: mkdir -p test-results
        
      - name: Run API Tests - All
        if: ${{ github.event.inputs.test_type == 'all' || github.event.inputs.test_type == '' }}
        run: npx playwright test
        env:
          BASE_URL: https://petstore.swagger.io/v2
          
      - name: Run User API Tests
        if: ${{ github.event.inputs.test_type == 'user' }}
        run: npx playwright test tests/user*
        env:
          BASE_URL: https://petstore.swagger.io/v2
          
      - name: Run Pet API Tests
        if: ${{ github.event.inputs.test_type == 'pet' }}
        run: npx playwright test tests/pet*
        env:
          BASE_URL: https://petstore.swagger.io/v2
          
      - name: Run Store API Tests
        if: ${{ github.event.inputs.test_type == 'store' }}
        run: npx playwright test tests/store*
        env:
          BASE_URL: https://petstore.swagger.io/v2
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dev-test-results-${{ github.run_number }}
          path: |
            test-results/
            playwright-report/
          retention-days: 7
          
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dev-playwright-report-${{ github.run_number }}
          path: playwright-report/
          retention-days: 7
          
  notification:
    runs-on: ubuntu-latest
    needs: api-tests
    if: failure()
    steps:
      - name: Send failure notification
        run: |
          echo "Dev tests failed at $(date)"
          echo "Check the test results for details"