name: QA Environment Tests

on:
  schedule:
    # Run daily at 6 AM UTC (Monday to Friday)
    - cron: '0 6 * * 1-5'
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - user
          - pet
          - store
          - smoke
      browser:
        description: 'Browser for tests'
        required: false
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit

jobs:
  api-tests:
    runs-on: ubuntu-latest
    environment: qa
    strategy:
      matrix:
        shard: [1, 2]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
          
      - name: Create test results directory
        run: mkdir -p test-results
        
      - name: Run API Tests - All (Sharded)
        if: ${{ github.event.inputs.test_type == 'all' || github.event.inputs.test_type == '' }}
        run: npx playwright test --shard=${{ matrix.shard }}/2
        env:
          BASE_URL: https://petstore.swagger.io/v2
          
      - name: Run User API Tests
        if: ${{ github.event.inputs.test_type == 'user' }}
        run: npx playwright test tests/user*
        env:
          BASE_URL: https://petstore.swagger.io/v2
          
      - name: Run Pet API Tests
        if: ${{ github.event.inputs.test_type == 'pet' }}
        run: npx playwright test tests/pet*
        env:
          BASE_URL: https://petstore.swagger.io/v2
          
      - name: Run Store API Tests
        if: ${{ github.event.inputs.test_type == 'store' }}
        run: npx playwright test tests/store*
        env:
          BASE_URL: https://petstore.swagger.io/v2
          
      - name: Run Smoke Tests
        if: ${{ github.event.inputs.test_type == 'smoke' }}
        run: npx playwright test --grep "@smoke"
        env:
          BASE_URL: https://petstore.swagger.io/v2
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: qa-test-results-shard-${{ matrix.shard }}-${{ github.run_number }}
          path: |
            test-results/
            playwright-report/
          retention-days: 14
          
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: qa-playwright-report-shard-${{ matrix.shard }}-${{ github.run_number }}
          path: playwright-report/
          retention-days: 14

  merge-reports:
    runs-on: ubuntu-latest
    needs: api-tests
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Download all reports
        uses: actions/download-artifact@v4
        with:
          pattern: qa-test-results-shard-*
          path: all-reports
          
      - name: Merge HTML reports
        run: npx playwright merge-reports --reporter html ./all-reports
        
      - name: Upload merged report
        uses: actions/upload-artifact@v4
        with:
          name: qa-merged-report-${{ github.run_number }}
          path: playwright-report/
          retention-days: 30
          
  notification:
    runs-on: ubuntu-latest
    needs: [api-tests, merge-reports]
    if: failure()
    steps:
      - name: Send failure notification
        run: |
          echo "QA tests failed at $(date)"
          echo "Check the merged test results for details"